services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: orders
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  migrate:
    image: migrate/migrate
    command: [ "-path", "/migrations", "-database",  "mysql://root:root@tcp(db:3306)/orders", "up" ]
    volumes:
      - ./internal/infra/database/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    restart: always
    ports:
      - "8000:8000"  # Porta para o servidor web
      - "50051:50051"  # Porta para o servidor gRPC
      - "8080:8080"  # Porta para o servidor GraphQL
    depends_on:
      - db
    environment:
      - DB_DRIVER=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=orders
      - DB_HOST=db
      - DB_PORT=3306
      - WEB_SERVER_PORT=8000
      - GRPC_SERVER_PORT=50051
      - GRAPHQL_SERVER_PORT=8080

volumes:
  mysql_data: